name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v6
        with: 
          configFile: commitlint.config.mjs

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      
      - name: Install dependencies
        run: npm ci  # Clean install
      
      - name: Check linting
        run: npm run lint
      
      - name: Check format with Prettier
        run: npm run format

      - name: Build the app
        run: npm run build

      - name: Run tests
        run: npm run test